steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  volumes:
  - name: 'vite-env'
    path: '/vite-env'
  args:
  - -ceu
  - |
    cat > /vite-env/.vite.env <<EOF
    VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
    VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
    VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
    VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}
    VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}
    VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}
    VITE_FIREBASE_FIRESTORE_DATABASE_ID=${_VITE_FIREBASE_FIRESTORE_DATABASE_ID}
    VITE_APP_URL=${_VITE_APP_URL}
    EOF

- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'DOCKER_BUILDKIT=1'
  volumes:
  - name: 'vite-env'
    path: '/vite-env'
  args: [
    'build',
    '--no-cache',
    '-t', '$_IMAGE_URI',
    '--secret', 'id=vite_env,src=/vite-env/.vite.env',
    '.'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  volumes:
  - name: 'vite-env'
    path: '/vite-env'
  args: ['-ceu', 'rm -f /vite-env/.vite.env']
images:
- '$_IMAGE_URI'

options:
  logging: CLOUD_LOGGING_ONLY
